<?php
/*namespace Nette;*/
if (!function_exists('_netteRequestCb2')) {
	function _netteRequestCb2($m)
	{
		return "$m[1]<a href='#' class='nette-toggler'>$m[2]($m[3]) " . '<abbr>&#x25ba;</abbr> </a><code class="nette-hidden">';
	}
}

?>
<h1>Presenter Tree</h1>

<div class="nette-inner">
	<table style="width: 100%;">
		<thead>
			<tr>
				<th rowspan="2">Presenter</th>
				<th rowspan="2">Action</th>
				<th colspan="3">Arguments</th>
			</tr>
			<tr>
				<th>Required</th>
				<th>Persistent</th>
				<th>Optional</th>
			</tr>
		</thead>
		<tbody>
			<?php renderPresenter($tree) ?>
		</tbody>
	</table>
</div>

<?php
function renderPresenter(array $array, $level = 1, $sub = 0)
{
	foreach ($array as $key_val => $value) {
		$offset = '';
		if (is_array($value) && !isset($value['__link'])){
			echo '<tr>';
			echo '<td rowspan="' . count($value) . '">' . $key_val . '</td>';
			renderPresenter($value, $level + 1, 1);
		}
		else {
			if ($sub != 1){
				echo '<tr>';
			}
			echo '<td><a href="' . $value['__link'] . '">' . $key_val . '</a></td><td>' . formatRequiredArgs($value['__arguments']['required']) . '</td><td>' . formatPersistentArgs($value['__arguments']['persistent']) . '</td><td>' . formatOptionalArgs($value['__arguments']['optional']) . '</td>';
			echo '</tr>';
		}
	}
}

function formatRequiredArgs($arguments)
{
	$output = '';
	$left = count($arguments);
	foreach ($arguments as $arg => $value) {
		$output .= '<span>$' . $arg . '</span>';

		$output .= '</span>';
		if ($left != 1) {
			$output .= ',&nbsp;';
			$left--;
		}
	}
	return $output;
}

function formatOptionalArgs($arguments)
{
	$output = '';
	$left = count($arguments);
	foreach ($arguments as $arg => $value) {
		$output .= '<span>$' . $arg . '</span>&nbsp;=&nbsp;';
		$output .= '<span style="color: #408045; font-style: italic !important;">';

		if ($value === TRUE) {
			$output .= 'TRUE';
		} elseif ($value === FALSE) {
			$output .= 'FALSE';
		} elseif ($value === NULL) {
			$output .= 'NULL';
		} elseif (is_string($value)) {
			$output .= '\'' . $value . '\'';
		} else {
			$output .= print_r($value, TRUE);
		}

		$output .= '</span>';
		if ($left != 1) {
			$output .= ',&nbsp;';
			$left--;
		}
	}
	return $output;
}

function formatPersistentArgs($arguments)
{
	$output = '';
	$left = count($arguments);
	foreach ($arguments as $reflection) {
		$output .= '<span>$' . $reflection->name . '</span>';
		if ($left != 1) {
			$output .= ',&nbsp;';
			$left--;
		}
	}
	return $output;
}
?>